FROM php:8.2-fpm

RUN apt-get update && apt-get install -y zlib1g-dev g++ git librabbitmq-dev libicu-dev zip libzip-dev libgeos-dev \
    && docker-php-ext-install intl opcache pdo pdo_mysql zip mysqli sockets \
    && pecl install apcu \
    && pecl install amqp \
    && docker-php-ext-enable apcu amqp

# Copy php.ini
COPY ./php.ini /usr/local/etc/php/php.ini

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Symfony CLI
RUN curl -1sLf 'https://dl.cloudsmith.io/public/symfony/stable/setup.deb.sh' | bash \
    && apt-get install symfony-cli

WORKDIR /var/www/symfony/

EXPOSE 8000
